devices:
  - name: "Roteador-3725"
    host: "192.168.166.182"  # <-- O IP de acesso via DHCP
    device_type: "cisco_ios"
    username: "admin"             # Seu usuÃ¡rio
    password: "cisco123"          # Sua senha
    global_delay_factor: 6